// Copyright 2026 Muhammad Waleed
// Licensed under the Apache License, Version 2.0
// Author: Muhammad Waleed

use crate::models::AgentStatus;
use std::time::Duration;
use tokio::time::sleep;
use tracing::{info, error};

// Tonic autogenerated proto client code will be in a module.
// Let's import the gRPC client and heartbeat request/response.
// Since tonic proto compilation happens in build.rs, the generated files are placed in OUT_DIR.
// We import them using tonic::include_proto!.
pub mod agent_grpc {
    tonic::include_proto!("taafi.agent");
}

use agent_grpc::agent_service_client::AgentServiceClient;
use agent_grpc::HeartbeatRequest;

pub struct HeartbeatService {
    agent_id: String,
    orchestrator_url: String,
    db_type: String,
}

impl HeartbeatService {
    pub fn new(agent_id: String, orchestrator_url: String, db_type: String) -> Self {
        Self {
            agent_id,
            orchestrator_url,
            db_type,
        }
    }

    pub async fn start(&self) {
        let orchestrator_url = self.orchestrator_url.clone();
        let agent_id = self.agent_id.clone();
        let db_type = self.db_type.clone();

        tokio::spawn(async move {
            info!("Starting Agent Heartbeat loop, target: {}", orchestrator_url);
            
            loop {
                sleep(Duration::from_secs(30)).await;
                
                let channel = tonic::transport::Endpoint::from_shared(orchestrator_url.clone());
                let channel = match channel {
                    Ok(chan) => chan.connect().await,
                    Err(e) => {
                        error!("Invalid orchestrator URL endpoint: {:?}", e);
                        continue;
                    }
                };

                let mut client = match channel {
                    Ok(conn) => AgentServiceClient::new(conn),
                    Err(e) => {
                        error!("Heartbeat: Failed to connect to orchestrator: {:?}", e);
                        continue;
                    }
                };

                let request = tonic::Request::new(HeartbeatRequest {
                    agent_id: agent_id.clone(),
                    status: "healthy".to_string(),
                    timestamp: chrono::Utc::now().timestamp_millis(),
                    db_type: db_type.clone(),
                });

                match client.heartbeat(request).await {
                    Ok(response) => {
                        let res = response.into_inner();
                        info!("Heartbeat ACK: ack = {}, sync_requested = {}", res.ack, res.request_sync);
                    }
                    Err(e) => {
                        error!("Failed to send heartbeat to orchestrator: {}", e);
                    }
                }
            }
        });
    }
}
