# Copyright 2026 Muhammad Waleed
# Licensed under the Apache License, Version 2.0
# Author: Muhammad Waleed

name: CI
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Protobuf
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - run: cargo build --verbose --workspace
      - run: cargo test --verbose --workspace
      - run: cargo clippy -- -D warnings
      - run: cargo fmt -- --check
